services:
  judge0-server:
    image: judge0/judge0:1.13.1
    ports:
      - "2358:2358"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: judge0
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: judge0secret
      ENABLE_BATCHED_SUBMISSIONS: "true"
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    privileged: true
    restart: on-failure

  judge0-workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: judge0
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: judge0secret
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    privileged: true
    restart: on-failure

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: algoarena
      POSTGRES_PASSWORD: localpassword
      POSTGRES_DB: algoarena
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pg_data:
